### PR TITLE
Theater: Balboa

### PR DESCRIPTION
**Pull request by crgrafton**
RHPS with The Bawdy Caste! (1)

### CODE REVIEW

**Comment by jaison2000b** [comment]
I had this one ready for the website... but I like their logo...
Next month we can use this one?
Balboa_website

Don't like the text you put underneath at all

**Comment by jaison2000b** [comment]
I'd rather have it say nothing underneath Feb 29th 2020

**Comment by crgrafton** [comment]
I think their logo looks way better than this image you made.

**Comment by crgrafton** [comment]
@jaison2000b you commented w/ no review.

**Pull request merged**
