### PR TITLE
add whitespace above social buttons

### LINKED ISSUE #79: bug: email overflow
image

### PR DESCRIPTION
**Pull request by xtoferprime**
## looks like this now:
Screenshot from 2019-10-27 23-30-22

## looks better with a little more spacing
Screenshot from 2019-10-27 23-30-52

also closes #79

### CODE REVIEW

**Comment by jaison2000b** [comment]
motherf*cker it wouldn't let me create  separate request to disable the button for tonight 😠 ...

**Comment by jaison2000b** [comment]
here is what the disable looks like 
image

**Comment by crgrafton** [comment]
> here is what the disable looks like
> image

That's the difference between `disable` and `disabled`.

If you want the button to be "turned off", use `.disable` and when you want it to not appear, use `.disabled`.

**Comment by jaison2000b** [comment]
DUMB

**Pull request closed without merging**
