### PR TITLE
feat(modal): create popup modal to display news link

### PR DESCRIPTION
**Pull request by crgrafton**
newsspotmodal v7

### CODE REVIEW

**Comment by jaison2000b** [comment]
I don't like the F13 font on the pop-up also it seems super plain I like the idea but also the whole full page automatic pop-up thing has become a norm for advertisements these days may I suggest a lower right corner? i'll work on the code later 
image

**Comment by jaison2000b** [comment]
k did the changes Not 100% satisfied with the result though, might come back to it later

**Comment by crgrafton** [comment]
Wow, so rude? Branch off when you want to do a different thing, don't co-opt my PR please...

**Comment by jaison2000b** [comment]
> Wow, so rude? Branch off when you want to do a different thing, don't co-opt my PR please...

:hanky:

**Pull request closed without merging**
